version: "3"

services:
  qdrant-database:
    networks:
      - app-network
    image: qdrant/qdrant:v1.7.4
    environment:
      - QDRANT__SERVICE__API_KEY=qdrant_pass
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage

  pg-db:
    networks:
      - app-network
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  upload-redis:
    image: redis
    container_name: upload-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  royal-road-server:
    networks:
      - app-network
    image: arguflow/royal-road
    build: ./
    ports:
      - "8090:8090"
    env_file:
      .env

  embedding-server:
    networks:
      - app-network
    image: arguflow/royal-road-embedding-server
    build: ./python_src/
    ports:
    - "5000:5000"

networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data:
  pgdata:
  redis-data:
